Repository numpy/numpy-stubs, pull requests merged in 2020-04, with the labels that each got.

#49 TST: add script to run tests
  runtests.py
Labels: maintenance

#50 MAINT: move things in `numeric.pyi` to the top-level `__init__.pyi`
  numpy-stubs/__init__.pyi
  numpy-stubs/core/numeric.pyi
Labels: maintenance

#51 ENH: add numerical constants
  numpy-stubs/__init__.pyi
  tests/reveal/constants.py
Labels: enhancement

#52 ENH: add integer constants
  numpy-stubs/__init__.pyi
  tests/reveal/constants.py
Labels: enhancement

#55 ENH: add __name__ attribue to ufuncs
  numpy-stubs/__init__.pyi
  tests/pass/ufuncs.py
Labels: enhancement

#58 Add Python 3.8 to the CI matrix
  .travis.yml
  test-requirements.txt
Labels: maintenance

#57 Added Warning and Exception annotations
  numpy-stubs/__init__.pyi
  tests/fail/warnings_and_errors.py
  tests/pass/warnings_and_errors.py
  tests/reveal/warnings_and_errors.py
Labels: enhancement

#61 DOC, TST: clarify that we intentionally ban lists in scalar constructors
  tests/fail/scalars.py
Labels: documentation

#62 MAINT: move __getattr__ to the top of __init__.pyi
  numpy-stubs/__init__.pyi
Labels: maintenance

#64 MAINT: run black on all files in CI
  .travis.yml
  runtests.py
  scripts/find_ufuncs.py
  tests/fail/scalars.py
  tests/fail/ufuncs.py
  tests/fail/warnings_and_errors.py
  tests/pass/scalars.py
  tests/pass/simple.py
  tests/pass/ufuncs.py
  tests/pass/warnings_and_errors.py
  tests/reveal/ndarray_conversion.py
  tests/reveal/scalars.py
  tests/test_stubs.py
Labels: maintenance

#69 TST: don't run tests in py2 mode
  tests/test_stubs.py
Labels: maintenance

#75 DOC: update testing README
  tests/README.md
Labels: documentation
