Repository numpy/numpy-stubs, pull requests merged in 2020-05, with the labels that each got.

#74 MAINT: Introduced a couple of fixes for the np.core.fromnumeric functions
  numpy-stubs/__init__.pyi
  tests/fail/fromnumeric.py
  tests/pass/fromnumeric.py
  tests/reveal/fromnumeric.py
Labels: maintenance

#70 TST: also run the code in "pass"
  setup.py
  tests/pass/ndarray_conversion.py
  tests/pass/ndarray_shape_manipulation.py
  tests/pass/scalars.py
  tests/pass/simple.py
  tests/test_stubs.py
Labels: tests

#66 ENH: get more specific about _ArrayLike, make it public
  numpy-stubs/__init__.pyi
  numpy-stubs/typing.pyi
  tests/fail/array_like.py
  tests/pass/array_like.py
  tests/reveal/fromnumeric.py
Labels: enhancement
